# Generated by Django 5.2 on 2025-05-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_genre_book_review_comment_userbookstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookstatus',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('reading', 'Currently Reading'), ('want', 'Want to Read')], max_length=50),
        ),
    ]
